// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WooCommerceProductManager.Data;

#nullable disable

namespace WooCommerceProductManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260913145800_AddProductPermalink")]
    partial class AddProductPermalink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("WooCommerceProductManager.Data.ProductEntity", b =>
                {
                    b.Property<long>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateModified")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ManageStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Permalink")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegularPrice")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SalePrice")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StockStatus")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("WooCommerceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LocalId");

                    b.HasIndex("WooCommerceId")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
